%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-mvsim
Version:        0.15.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mvsim package

License:        BSD
URL:            https://wiki.ros.org/mvsim
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python%{python3_pkgversion}-devel
Requires:       cppzmq-devel
Requires:       protobuf-compiler
Requires:       protobuf-devel
Requires:       pybind11-devel
Requires:       python3-libs
Requires:       python3-pip
Requires:       python3-protobuf
Requires:       ros-kilted-mrpt-libgui
Requires:       ros-kilted-mrpt-libmaps
Requires:       ros-kilted-mrpt-libposes
Requires:       ros-kilted-mrpt-libros-bridge
Requires:       ros-kilted-mrpt-libtclap
Requires:       ros-kilted-nav-msgs
Requires:       ros-kilted-ros2launch
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-stereo-msgs
Requires:       ros-kilted-tf2
Requires:       ros-kilted-tf2-geometry-msgs
Requires:       ros-kilted-visualization-msgs
Requires:       unzip
Requires:       wget
Requires:       ros-kilted-ros-workspace
BuildRequires:  boost-devel
BuildRequires:  boost-python%{python3_pkgversion}-devel
BuildRequires:  cmake3
BuildRequires:  cppzmq-devel
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  pybind11-devel
BuildRequires:  python3-libs
BuildRequires:  python3-pip
BuildRequires:  python3-protobuf
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-ament-cmake-gmock
BuildRequires:  ros-kilted-ament-cmake-gtest
BuildRequires:  ros-kilted-ament-cmake-xmllint
BuildRequires:  ros-kilted-mrpt-libgui
BuildRequires:  ros-kilted-mrpt-libmaps
BuildRequires:  ros-kilted-mrpt-libposes
BuildRequires:  ros-kilted-mrpt-libros-bridge
BuildRequires:  ros-kilted-mrpt-libtclap
BuildRequires:  ros-kilted-nav-msgs
BuildRequires:  ros-kilted-ros-environment
BuildRequires:  ros-kilted-sensor-msgs
BuildRequires:  ros-kilted-stereo-msgs
BuildRequires:  ros-kilted-tf2
BuildRequires:  ros-kilted-tf2-geometry-msgs
BuildRequires:  ros-kilted-visualization-msgs
BuildRequires:  unzip
BuildRequires:  wget
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-ament-lint-common
%endif

%description
A lightweight multivehicle simulation framework.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Mon Dec 29 2025 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.15.0-1
- Autogenerated by Bloom

* Mon Nov 10 2025 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.14.2-1
- Autogenerated by Bloom

* Fri Nov 07 2025 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.14.1-1
- Autogenerated by Bloom

* Sun Jul 06 2025 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.14.0-1
- Autogenerated by Bloom

* Wed May 28 2025 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.13.3-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.13.2-2
- Autogenerated by Bloom

* Wed Feb 05 2025 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.13.2-1
- Autogenerated by Bloom

* Tue Feb 04 2025 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.13.1-1
- Autogenerated by Bloom

* Tue Dec 24 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.13.0-1
- Autogenerated by Bloom

* Wed Dec 04 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.12.0-1
- Autogenerated by Bloom

* Thu Oct 17 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.11.1-1
- Autogenerated by Bloom

* Sat Oct 12 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.11.0-1
- Autogenerated by Bloom

* Wed Aug 28 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.10.0-1
- Autogenerated by Bloom

* Wed May 08 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.9.4-1
- Autogenerated by Bloom

* Wed Apr 24 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.9.3-1
- Autogenerated by Bloom

* Thu Mar 21 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.9.2-1
- Autogenerated by Bloom

* Thu Mar 14 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.9.1-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.8.3-2
- Autogenerated by Bloom

